### ISSUE TITLE
Double headers after update to 0.5 version

### ISSUE THREAD

**Issue by arunnbabu81** [crazko/krystal#46] opened 2022-03-13 18:12 UTC
![image](https://user-images.githubusercontent.com/67494083/158073045-c78900fc-a38b-4882-bee1-424ad10e14ad.png)

After the update, my wiki was looking like this. I had to remove the `$:/tags/PageTemplate` from the `$:/plugins/rmnvsl/krystal/header-small` to get it removed. 

I had done some tweaks in my wiki to make Krystal and captivate theme compatible. Can that be responsible for this. You can see a test wiki at this site - https://krystal.tiddlyhost.com/

**Comment by crazko** [comment] 2022-03-13 18:43
Yes, your changes do overwrite the new functionality (see https://github.com/crazko/krystal/issues/32#issuecomment-1066139441). There are now two headers, one is visible on wide viewport, second one on narrow viewport. Their visibility is defined in [$:/plugins/rmnvsl/krystal/header.css](https://krystal.tiddlyhost.com/#%24%3A%2Fplugins%2Frmnvsl%2Fkrystal%2Fheader.css) which is modified in your TW instance.

You can check https://github.com/crazko/krystal/commit/79388e225c30b261596883029ff245fd75960941 to know what has changed. Hopefully you will be able to update your modification based on that.

**Comment by crazko** [comment] 2022-03-14 07:27
Closing this one, as it is not a bug. Feel free to add more comments if you need more help.

**Closed by crazko** 2022-03-14 07:27 UTC
