### ISSUE TITLE
TypeError: document.querySelector(...) is null 

### ISSUE THREAD

**Issue by arunnbabu81** [crazko/krystal#53] opened 2022-06-13 17:09 UTC
Here is an attempt to make krystal and multicolumn plug in work together.
This is done using the [ensemble](https://burningtreec.github.io/tiddlywiki-multi-columns/#%24%3A%2Fplugins%2FBTC%2Ftiddlywiki-multi-columns%2Fui%2FSideBarTabs%2FEnsemble) feature of multicolumn - you can save a particular layout, storyview, stylesheets tiddlers, pagetemplate to a particular ensemble. So when we load that particular ensemble, all these will be automatically loaded.

Check this demo - https://multicolumn-krystal.tiddlyhost.com/

But I encountered one problem - 

<img width="1843" alt="image" src="https://user-images.githubusercontent.com/67494083/173407257-36ac3c63-78cb-49ad-84d1-f73678ec287c.png">

Is this related to krystal plug in.

**Comment by arunnbabu81** [comment] 2022-07-17 20:24
@crazko Can you take a look at this.

Use this link. https://multicolumn-krystal.tiddlyhost.com/

You will see an error message on opening the wiki.

<img width="1874" alt="image" src="https://user-images.githubusercontent.com/67494083/179423456-39108cca-e0ac-44d5-9297-a344fe84428c.png">

Close the error message and click on the Krystal link in the topbar.

<img width="1886" alt="image" src="https://user-images.githubusercontent.com/67494083/179423531-351056db-bd6b-4849-9aac-3d6821b3b251.png">

Now open few tiddlers in the Horizontal layout

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/67494083/179423555-8b30fb96-4ddc-4078-8596-0bd54362bd99.png">

In this image, you can see that I have opened many tiddlers, but none of them show their titles.
Any possible reason for the `error message and tiddler titles missing ` you can think of

**Comment by ericworks** [comment] 2022-07-18 04:19
Hi @arunnbabu81 ,

The functionality of horizontal scrolling, stacking tiddlers, vertical title for
stacked tiddlers, etc, is implemented in `krystal/plugin.js` basically. From 
your demo site, `header()` function in `krystal/plugin.js` is complaining a 
`TypeError`, which is due to missing `.krystal-header` element (that top 
navbar). This is a sign of something going wrong and it may be the cause of 
your reported issue. I didn't spend time in debugging your demo and couldn't 
provide you with more detail. However, I'm guessing it's a plugin conflict.

As a suggestion, enabling multiple plugins which serve a similar/same purpose, 
may impose some non-trivial code conflicts which can take time to debug and 
resolve. If you find nothing buggy in the two conflicting plugins themselves, 
in most cases you probably want to write a new plugin with some glue code to 
make them seamlessly work together. Also, if you find something buggy in Krystal
itself, or any ideas on improving existing code-base to make it more compatible
with other plugins *in general*, you are welcome to create a new issue or PR.

This is not a bug related to Krystal. I suggest closing this issue.

**Comment by arunnbabu81** [comment] 2022-07-18 08:46
As I told in the first post this is an attempt to see whether multicolumn and Krystal plug in will work together. And the error message seen is due the conflict between these two plug ins. I was interested in knowing whether this conflict can be resolved?

**Closed** 2022-08-13 20:40 UTC

**Comment by linonetwo** [comment] 2024-10-10 14:34
Still a bug when switch to an alternative layout when krystal is installed.
